module.exports = {
    "RECIPE_EN_GB" : {
        "the blue room": "<audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/transformersALEXA.mp3\"/> the blue room is in quay house, on the fifth floor. Its one of my favourite places here!",
        "the blue wool": "<audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/transformersALEXA.mp3\"/>the blue room is in quay house, on the fifth floor. Its one of my favourite places here!",
        "blue room": "the blue room is in quay house, on the fifth floor. Its one of my favourite places here! <audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/transformersALEXA.mp3\"/>",
        "blueroom": "the blue room is in quay house, on the fifth floor. Its one of my favourite places here! <audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/transformersALEXA.mp3\"/>",
        "production services": "production services is situated in bridge house, on the ground floor, take a left past the lifts. say hello to andy for me! ",
        "backstage": "backstage is situated in bridge house, on the ground floor past the lifts.",
        "a question of sport": "a question of sport is situated in bridge house on the first floor <audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/qosALEXA.mp3\"/>",
        "waterloo road": "<audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/waterlooALEXA.mp3\"/> waterloo road is situated in bridge house on the first floor",
        "bbc iplayer": "bbc iplayer is situated in bridge house on the first floor, ",
        "iplayer": "bbc iplayer is situated in bridge house on the first floor, ",
        "bbc proms": "bbc proms is situated in bridge house on the first floor. ",
        "gavin and stacey": "gavin and stacey is situated in bridge house on the first floor. anyone fancy an omlette? <audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/gavinstacyALEXA.mp3\"/>",
        "kevin spacey": "gavin and stacey is situated in bridge house on the first floor. anyone fancy an omlette? <audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/gavinstacyALEXA.mp3\"/>",
        "bitesize": "<audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/hello.mp3\"/> bitesize is situated in bridge house on the second floor. Bitesize gets 3 million unique visits every week! Every days a school day. ",
        "coast": "coast is situated in bridge house on the second floor",
        "aquarium": "you will find the aquarium in bridge house on the second floor. i hope your meeting goes swimmingly",
        "citizen khan": "citizen khan is situated in bridge house on the third floor.",
        "eastenders": "<audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/eastendersALEXA.mp3\"/> eastenders is situated in bridge house on the third floor. Now sling yer hook!",
        "in the night garden": "in the night garden is situated in bridge house on the fourth floor",
        "fighting talk": "fighting talk is situated in bridge house on the fourth floor",
        "football focus": "football focus is situated in bridge house on the fourth floor",
        "blue peter": "blue peter is situated in bridge house on the fifth floor",
        "wimbledon": "wimbledon is situated in bridge house, on the fifth floor",
        "today": "today is situated in bridge house, on the fifth floor",
        "bbc radio manchester": "bbc radio manchester, the meeting room that is, is situated in bridge house on the sixth floor.",
        "peter kosminsky": "peter kosminsky is situated in bridge house, on the sixth floor.",
        "katie adie": "kate aydee is situated in bridge house on the sixth floor. a great lady, kate aydee.",
        "kate adie": "kate aydee is situated in bridge house on the sixth floor. a great lady, kate aydee.",
        "peter bazalgette": "you will find the meeting room peter bazalgette in bridge house all the way up on the sixth floor.",
        "lenny henry": "lenny henry the meeting room that is, is situated in bridge house on the sixth floor. katanga!",
        "stephen merchant": "stephen merchant, the meeting room named after the bristolian comedy genius, is to be found on the sixth floor of bridge house. ",
        "doctor who": "<audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/drwhoALEXA.mp3\"/> doctor who is to be found in dock house on the first floor. if youre running late, why not step into a tardis and come back earlier?",
        "sports report": "sports report is to be found in dock house on the first floor.",
        "countryfile": "countryfile is to be found in dock house on the first floor.",
        "match of the day": "match of the day is to be found in dock house on the second floor.",
        "up all night": "up all night is to be found in dock house on the second floor.",
        "the one show": "you will find the one show in dock house on the second floor.",
        "sports personality of the year": "sports personality of the year is situated in dock house on the second floor",
        "little britain": "little britain is in dock house on the second floor. ",
        "dragons den": "dragons den is in dock house on the third floor. i want ten percent shares in whatever your pitching!",
        "planet earth": "planet earth is in dock house on the third floor.",
        "pudsey": "pudsey is in dock house on the third floor. last year, children in need raised 46 million pounds!",
        "north west tonight": "north west tonight is in dock house on the fourth floor. here's a fact, north west tonight has been broadcasting for 33 years!",
        "womens hour":"womens hour is in dock house, on the fourth floor. womens hour was first broadcast on 7 october 1946",
        "zingzillas":"youll find the zingzillas meeting room, in dock house, on the fourth floor!",
        "imaginarium":"the alan turing imaginarium, is on the sixth floor of dock house. it has amazing views, and is named after manchester's famous computer pioneer",
        "top gear": "top gears is situated in quay house, on the ground floor, left behind the stairs",
        "radio one big weekend": "radio one big weekend is situated in quay house, on the first floor",
        "tracey beaker": "you will find tracey beaker in quay house, on the first floor",
        "the little painting challenge room": "the little painting challenge room is in quay house, on the second floor",
        "horrible histories": "horrible histories is in quay house, on the third floor",
        "strictly come dancing": "strictly come dancing is in quay house, on the third floor <audio src=\"https://s3-eu-west-1.amazonaws.com/alexasoundsamples/strictlyALEXA.mp3\"/> ",
        "brian redhead": "brian redhead is on the fourh floor of quay house. its on the left hand side of the atrium, toward the back of the building.",
        "main q5": "main q5 is on the fifth floor of quay house. ",
        "q5 meeting space": "q5 meeting space is on the fifth floor of quay house. when you come out of the lifts, turn towards the atrium and its on your left. cheers!",
        "q5 event space": "q5 event space is on the fifth floor of quay house. when you come out of the lifts, turn towards the atrium and its on your left. cheers!",
        "corner q5": "corner q5 is on the fifth floor of quay house, at the far end on the left next to the blue room."
         },
    "RECIPE_EN_US" : {
        "the blue room": "The Blue Room is in quay house, on the fifth floor. Its one of my favourite places here!",
        "blue room": "The Blue Room is in quay house, on the fifth floor. Its one of my favourite places here!",
        "production services": "production services is situated in bridge house, on the ground floor, take a left past the lifts. say hello to andy for me! ",
        "backstage": "backstage is situated in bridge house, on the ground floor past the lifts.",
        "a question of sport": "a question of sport is situated in bridge house on the first floor",
        "waterloo road": "is situated in bridge house on the first floor",
        "bbc iplayer": "bbc iplayer is situated in bridge house on the first floor, ",
        "iplayer": "bbc iplayer is situated in bridge house on the first floor, ",
        "bbc proms": "bbc proms is situated in bridge house on the first floor. ",
        "gavin and stacey": "gavin and stacey is situated in bridge house on the first floor. go on gavlaa!",
        "bitesize": "bitesize is situated in bridge house on the second floor",
        "coast": "coast is situated in bridge house on the second floor",
        "aquarium": "you will find the aquarium in bridge house on the second floor. i hope your meeting goes swimmingly",
        "citizen khan": "citizen khan is situated in bridge house on the third floor.",
        "eastenders": "eastenders is situated in bridge house on the third floor. rickayy!",
        "in the night garden": "in the night garden is situated in bridge house on the fourth floor",
        "fighting talk": "fighting talk is situated in bridge house on the fourth floor",
        "football focus": "football focus is situated in bridge house on the fourth floor",
        "blue peter": "blue peter is situated in bridge house on the fifth floor",
        "wimbledon": "wimbledon is situated in bridge house, on the fifth floor",
        "today": "today is situated in bridge house, on the fifth floor",
        "bbc radio manchester": "bbc radio manchester, the meeting room that is, is situated in bridge house on the sixth floor.",
        "peter kosminsky": "peter kosminsky is situated in bridge house, on the sixth floor.",
        "katie adie": "katie aydee is situated in bridge house on the sixth floor. a great lady, kate aydee.",
        "kate adie": "kate aydee is situated in bridge house on the sixth floor. a great lady, kate aydee.",
        "peter bazalgette": "you will find the meeting room peter bazalgette in bridge house all the way up on the sixth floor.",
        "lenny henry": "lenny henry the meeting room that is, is situated in bridge house on the sixth floor. katanga!",
        "stephen merchant": "stephen merchant, the meeting room named after the bristolian comedy genius is to be found on the sixth floor of bridge house. ",
        "doctor who": "doctor who is to be found in dock house on the first floor. if youre running late, why not step into a tardis and come back earlier?",
        "sports report": "sports report is to be found in dock house on the first floor.",
        "countryfile": "countryfile is to be found in dock house on the first floor.",
        "match of the day": "match of the day is to be found in dock house on the second floor.",
        "up all night": "up all night is to be found in dock house on the second floor.",
        "the one show": "you will find the one show in dock house on the second floor.",
        "sports personality of the year": "sports personality of the year is situated in dock house on the second floor",
        "little britain": "little britain is in dock house on the second floor. ",
        "dragons den": "dragons den is in dock house on the third floor. i want ten percent shares in whatever your pitching!",
        "planet earth": "planet earth is in dock house on the third floor.",
        "pudsey": "pudsey is in dock house on the third floor. last year, children in need raised 46 million pounds!",
        "north west tonight": "north west tonight is in dock house on the fourth floor. here's a fact, north west tonight has been broadcasting for 33 years!",
        "womens hour":"womens hour is in dock house, on the fourth floor. womens hour was first broadcast on 7 october 1946",
        "zingzillas":"youll find the zingzillas meeting room, in dock house, on the fourth floor!",
        "imaginarium":"the alan turing imaginarium, is on the sixth floor of dock house. it has amazing views, and is named after manchester's famous computer pioneer",
        "top gear": "top gear is situated in quay house, on the ground floor, left behind the stairs",
        "radio one big weekend": "radio one big weekend",
        "tracey beaker": "tracey beaker",
        "the little painting challenge room": "the little painting challenge room",
        "horrible histories": "horrible histories",
        "strictly come dancing": "strictly come dancing",
        "brian redhead": "brian redhead is on the fourh floor of quay house. its on the left hand side of the atrium, toward the back of the building.",
        "main q5": "main q5 is on the fifth floor of quay house. ",
        "q5 meeting space": "q5 meeting space is on the fifth floor of quay house. when you come out of the lifts, turn towards the atrium and its on your left. cheers!"
          },
    "RECIPE_DE_DE" : {
        "schneegolem": "Ein Schneegolem kann erschaffen werden, indem ein Kürbis auf zwei auf dem Boden stehende Schneeblöcke gesetzt wird.",
        "quarzsäule": "Eine Quarzsäule erhält man, indem in Minecraft ein Quarzblock auf einem Quarzblock platziert wird.",
        "feuerwerksrakete": "Eine Feuerwerksrakete kann gecraftet werden, indem ein Feuerwerksstern in das linke mittlere Feld, ein Blatt Papier in das mittlere Feld und Schwarzpulver in das rechte mittlere Feld der Werkbank gelegt wird. Ähnlich wie bei einem Feuerwerksstern kann einer Feuerwerksrakete in der unteren Reihe zusätzliches Schwarzpulver hinzugefügt werden, um die Dauer der Rakete zu verlängern.",
        "kaninchenragout": "Kaninchenragout kann gecraftet werden, indem ein Gekochtes Kaninchen in das obere mittlere Feld, eine Karotte in das linke mittlere Feld, eine Ofenkartoffel in das Feld ganz in der Mitte, eine beliebige Pilzart in das rechte mittlere Feld und eine Schüssel in des untere mittlere Feld platziert wird.",
        "kessel": "Ein Kessel kann hergestellt werden, indem Eisenbarren in alle Felder der Werkbank mit Ausnahme des oberen mittleren Feldes und des Feldes ganz in der Mitte gelegt werden.",
        "steinschaufel": "Jede Art von Schaufel lässt sich craften, indem auf der Werkbank das gewünschte Material in das obere mittlere Feld gelegt wird und dann Stöcke in die beiden direkt darunter befindlichen Felder platziert werden.",
        "roter teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.",
        "buch und feder": "Buch und Feder kann gecraftet werden, indem in der Werkbank ein Buch in das linke mittlere Feld, ein Tintenbeutel in das Feld ganz in der Mitte und eine Feder in das untere mittlere Feld platziert werden.",
        "rahmen": "Ein Rahmen kann gecraftet werden, indem Leder in das Feld ganz in der Mitte platziert und dann von acht Stöcken umgeben wird.",
        "karte": "Eine Karte kann gecraftet werden, indem ein Kompass in das Feld ganz in der Mitte platziert und dann von acht Blättern Papier umgeben wird.",
        "klebriger Kolben": "Ein klebriger Kolben kann gecraftet werden, indem ein Schleimball im Craftingfeld über einem Kolben platziert wird.",
        "brot": "Brot kann gecraftet werden, indem eine Reihe der Werkbank vollständig mit Weizen gefüllt wird.",
        "holzspitzhacke": "Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert wird.",
        "schere": "Eine Schere kann gecraftet werden, indem zwei Eisenbarren diagonal zueinander platziert werden.",
        "rohes rindfleisch": "Rohes Rindfleisch wird beim Tod einer Kuh oder Mooshroom gedroppt.",
        "glatter roter sandstein": "Glatter roter Sandstein kann gecraftet werden, indem im Craftingfeld vier rote Sandsteinblöcke in einem 2x2-Raster platziert werden.",
        "prismarinkristalle": "Prismarinkristalle erhält man, indem Wächter und große Wächter besiegt werden.",
        "eichenholzstufe": "Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.",
        "holzschwert": "Jede Art von Schwert lässt sich craften, indem auf einer Werkbank das gewünschte Material in das obere mittlere Feld sowie das Feld ganz in der Mitte platziert und dann ein Stock in das darunter befindliche Feld gelegt wird.",
        "treppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "tropenholzzaun": "Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "aktivierungsschiene": "Eine Aktivierungsschiene kann gecraftet werden, indem eine Redstone-Fackel in das Feld ganz in der Mitte, Stöcke darüber und darunter und dann sechs Eisenbarren in den übrigen Feldern der Werkbank platziert werden.",
        "ackerboden": "Ackerboden kann hergestellt werden, indem der Boden mit einer Hacke bearbeitet wird.",
        "golderz": "Golderz erhält man, indem Golderzblöcke mit einer Spitzhacke aus Eisen oder einem hochwertigerem Material abgebaut werden.",
        "andesit": "Andesit kann mit einer Spitzhacke abgebaut werden, oder es lässt sich craften, indem in der Werkbank Diorit neben Bruchstein platziert wird.",
        "roter farbstoff": "Roter Farbstoff kann gecraftet werden, indem eine Mohnblume in die Werkbank gelegt wird.",
        "eisenaxt": "Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "hellblauer farbstoff": "Hellblauer Farbstoff kann gecraftet werden, indem im Craftingfeld Lapislazuli neben Knochenmehl platziert wird.",
        "grauer farbstoff": "Grauer Farbstoff kann gecraftet werden, indem im Craftingfeld Knochenmehl neben einem Tintenbeutel platziert wird.",
        "blau gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "eiserne pferderüstung": "Eine Pferderüstung kann zufällig in Verliesen, Netherfestungen, bei Schmieden, in Dschungeltempeln, Wüstentempeln und Truhen in Festungen gefunden werden.",
        "rot gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "ziegeltreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "goldene hose": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "schwarzeichenzauntor": "Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "witherschädel": "Schädel erhält man, indem man mit einem geladenen Creeper die Kreatur explodieren lässt, deren Schädel man möchte.",
        "spinnenauge": "Ein Spinnenauge droppt zufällig beim Töten von Spinnen oder Hexen.",
        "magenta gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "braun gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "kürbiskuchen": "Ein Kürbiskuchen kann gecraftet werden, indem in der Werkbank ein Kürbis in das linke mittlere Feld, Zucker in das Feld ganz in der Mitte und ein Ei in das untere mittlere Feld platziert werden.",
        "schneeball": "Einen Schneeball erhält man, indem Schnee mit einer Schaufel zerkleinert wird.",
        "jukebox": "Eine Jukebox wird hergestellt, indem ein Diamant in einer Werkbank im mittleren Feld platziert und von Holzbrettern umgeben wird.",
        "sand": "Sand erhält man, indem Sandblöcke zerkleinert werden.",
        "toter busch": "Tote Büsche, auch nur Büsche genannt, werden mit einer Schere erhalten.",
        "ziegelstufe": "Eine Ziegelstufe kann hergestellt werden, indem in einer Werkbank drei Ziegelstein-Blöcke in einer Reihe platziert werden.",
        "seerosenblatt": "Seerosenblätter kommen natürlich auf Wasser in Sümpfen oder unterirdischen Seen vor.",
        "lederhose": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "bemooste bruchsteinmauer": "Eine Bemooste Bruchsteinmauer wird gecraftet, indem sechs Bemooste Bruchsteine in die beiden unteren Reihen einer Werkbank platziert werden.",
        "schallplatte 11": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "violett gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "magenta gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "schallplatte mall": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "tropenholz": "Alle Holzarten können erhalten werden, indem der entsprechende Baum zerstört wird.",
        "diamantaxt": "Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "leere karte": "Eine Karte kann gecraftet werden, indem ein Kompass in das Feld ganz in der Mitte platziert und dann von acht Blättern Papier umgeben wird.",
        "steindruckplatte": "Eine Steindruckplatte lässt sich craften, indem zwei glatte Steine horizontal nebeneinander in das Craftingfeld gelegt werden.",
        "falltür": "Falltüren können entweder mit Holzbrettern oder Eisenbarren gecraftet werden. Um eine Holzfalltür zu craften, werden Holzbretter in alle Felder der beiden unteren Reihen platziert. Um eine Eisenfalltür zu craften, werden Eisenbarren in einem 2x2-Raster in einer Werkbank platziert.",
        "goldstiefel": "Alle Stiefel lassen sich craften, indem das gewünschte Material im linken mittleren, linken unteren, rechten mittleren und rechten unteren Feld einer Werkbank platziert wird.",
        "schallplatte stall": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "redstone-kabel": "Das Redstone-Kabel ist einfach Redstone, das auf dem Boden platziert wird.",
        "kolben": "Ein Kolben kann gecraftet werden, indem ein Eisenbarren im Feld ganz in der Mitte, Redstone im unteren mittleren Feld, Holzbretter in allen Felder der oberen Reihe und Bruchstein in den übrigen Feldern platziert werden.",
        "weiß gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "antriebslore": "Eine Antriebslore wird gecraftet, indem ein Ofen in einem Craftingfeld über einer Lore platziert wird.",
        "zucker": "Zucker kann erhalten werden, indem Zuckerrohr in einer Werkbank platziert wird.",
        "kettenhemd": "Kettenrüstung kann nur durch den Handel mit einem Dorfbewohner oder einem seltenen Drop von einer Kreatur erhalten werden.",
        "feder": "Federn können zufällig durch das Töten von Hühnern erhalten werden.",
        "hellblau gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "eichenholzzaun": "Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "steinspitzhacke": "Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert wird.",
        "rosa teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.",
        "monsterspawner": "Monsterspawner können in Minecraft nur durch Cheats erhalten werden.",
        "goldene karotte": "Eine Goldene Karotte kann gecraftet werden, indem eine Karotte in das Feld ganz in der Mitte gelegt und dann von acht Goldklumpen umgeben wird.",
        "stock": "Ein Stock kann gecraftet werden, indem in einem Craftingfeld ein Holzbrett über einem Holzbrett platziert wird.",
        "diamantblock": "Ein Diamantblock kann gecraftet werden, indem Diamanten in allen Feldern einer Werkbank platziert werden.",
        "grün gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "gebratenes hühnchen": "Rohes Hühnchen kann gebraten werden, indem es in einem Ofen geschmolzen wird. Alternativ dazu besteht die Chance, dass Gebratenes Hühnchen droppt, wenn ein brennendes Huhn stirbt.",
        "schallplatte 13": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "holzfalltür": "Eine Holzfalltür wird gecraftet, indem Holzbretter in einer Werkbank in alle Felder der beiden unteren Reihen platziert werden.",
        "eichenzauntor": "Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "werkbank": "Eine Werkbank kann gecraftet werden, indem Holzbretter in einem 2x2-Raster in einem Craftingfeld platziert werden.",
        "netherquarzerz": "Netherquarzerz kann zufällig im Nether gefunden werden. Um das Erz anstelle von Netherquarz zu erhalten, muss eine mit Behutsamkeit verzauberte Spitzhacke verwendet werden.",
        "goldschwert": "Jede Art von Schwert lässt sich craften, indem auf einer Werkbank das gewünschte Material in das obere mittlere Feld sowie das Feld ganz in der Mitte platziert und dann ein Stock in das darunter befindliche Feld gelegt wird.",
        "grau gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "hellblau gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "diamantstiefel": "Alle Stiefel lassen sich craften, indem das gewünschte Material im linken mittleren, linken unteren, rechten mittleren und rechten unteren Feld einer Werkbank platziert wird.",
        "steinhacke": "Alle Arten von Hacken können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke und obere mittlere Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "steinkohle": "Steinkohle erhält man, indem Steinkohleblöcke mit einer mit Behutsamkeit verzauberten Spitzhacke abgebaut werden.",
        "schwarzeichenlaub": "Alles Laub kann erhalten werden, indem eine Schere mit dem gewünschten Laub benutzt wird.",
        "tnt": "TNT kann gecraftet werden, indem in einem Craftingfeld Schwarzpulver X-förmig platziert und dann Sand in alle übrigen Felder gelegt wird.",
        "ziegel": "Ein Ziegel kann gecraftet werden, indem Ton in einem Ofen geschmolzen wird.",
        "kartoffel": "Kartoffeln können selten durch das Töten von Zombies erhalten werden, oder sie können zum Anpflanzen in Dörfern gefunden werden.",
        "oranger teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.",
        "tintenbeutel": "Ein Tintenbeutel kann durch das Töten eines Tintenfischs erhalten werden.",
        "redstone": "Redstone erhält man, indem Redstonerz mit einer Spitzhacke aus Eisen oder einem hochwertigerem Material abgebaut wird.",
        "schwarzeichenholz": "Alle Holzarten können erhalten werden, indem der entsprechende Baum zerstört wird.",
        "diorit": "Diorit kann mit einer Spitzhacke abgebaut oder gecraftet werden, indem in der Werkbank in einem 2x2-Raster Bruchstein mit Netherquarz kombiniert wird.",
        "grau gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "tropenholzzauntor": "Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "magenta wolle": "Magenta Wolle kann gecraftet werden, indem in einem Craftingfeld Magenta Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "erde": "Erde erhält man, indem Gras oder Erde mit einer Schaufel zerkleinert wird.",
        "rüstungsständer": "Ein Rüstungsständer kann mit sechs Stöcken und einer Steinstufe gecraftet werden. Drei Stöcke werden in der obersten Reihe platziert. Die übrigen drei Stöcke werden jeweils im unteren linken und unteren rechten Feld sowie im Feld ganz in der Mitte platziert. Die Steinstufe wird wird im unteren mittleren Feld platziert.",
        "gebratener fisch": "Gebratener Fisch wird erhalten, indem Fisch in einem Ofen gebraten wird.",
        "hebel": "Ein Hebel kann gecraftet werden, indem in einem Craftingfeld ein Stock über Bruchstein platziert wird.",
        "leine": "Eine Leine kann gecraftet werden, indem ein Schleimball in einer Werkbank in das Feld ganz in der Mitte und dann Fäden in das obere linke, obere mittlere, mittlere linke und untere rechte Feld platziert werden.",
        "gebratenes kaninchen": "Gebratenes Kaninchen wird erhalten, indem Rohes Kaninchen in einem Ofen gebraten wird. Alternativ dazu besteht die Chance, dass Gebratenes Kaninchen droppt, wenn ein brennendes Kaninchen stirbt.",
        "tropenholztreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "trichterlore": "Eine Trichterlore wird gecraftet, indem ein Trichter in einer Werkbank über einer Lore platziert wird.",
        "fermentiertes Spinnenauge": "Fermentiertes Spinnenauge kann gecraftet werden, indem in einer Werkbank ein brauner Pilz im mittleren linken Feld, Zucker im Feld ganz in der Mitte und ein Spinnenauge im unteren mittleren Feld platziert werden.",
        "roher fisch": "Roher Fisch kann zufällig durch Angeln erhalten werden.",
        "braun gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "schild": "Ein Schild kann gecraftet werden, indem Holzbretter in den beiden oberen Reihen und ein Stock im unteren mittleren Feld platziert werden.",
        "trichter": "Ein Trichter kann gecraftet werden, indem in einer Werkbank eine Truhe im Feld ganz in der Mitte und dann Eisenbarren in jedem Feld mit Ausnahme des oberen mittleren, des linken unteren und rechten unteren Feldes platziert werden.",
        "lohenrute": "Lohenruten können zufällig durch das Töten von Lohen erhalten werden.",
        "redstone-komparator": "Ein Redstone-Komparator kann gecraftet werden, indem in der Werkbank drei glatte Steine in der unteren Reihe, ein Netzerquarz im Feld ganz in der Mitte und drei Redstone-Fackeln um den Netzerquarz herum platziert werden.",
        "knochen": "Knochen können durch das Töten von Skeletten erhalten werden.",
        "goldene pferderüstung": "Eine Pferderüstung kann zufällig in Verliesen, Netherfestungen, bei Schmieden, in Dschungeltempeln, Wüstentempeln und Truhen in Festungen gefunden werden.",
        "goldbeinschutz": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "schiene": "Eine Schiene kann gecraftet werden, indem in einer Werkbank ein Stock im Feld ganz in der Mitte und Eisenbarren senkrecht in der ersten und letzten Spalte platziert werden.",
        "weizenkörner": "Weizenkörner können durch die Ernte von Weizen erhalten werden.",
        "birkenholzzaun": "Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "violett gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "goldharnisch": "Alle Brustrüstungen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des oberen mittleren Feldes in einer Werkbank platziert wird.",
        "lederstiefel": "Alle Stiefel lassen sich craften, indem das gewünschte Material im linken mittleren, linken unteren, rechten mittleren und rechten unteren Feld einer Werkbank platziert wird.",
        "diamantschaufel": "Jede Art von Schaufel lässt sich craften, indem auf der Werkbank das gewünschte Material in das obere mittlere Feld gelegt wird und dann Stöcke in die beiden direkt darunter befindlichen Felder platziert werden.",
        "lederhose": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "roter sand": "Roter Sand kann in Tafelberg-Biomen gefunden werden.",
        "ranken": "Ranken können nur mit einer Schere geerntet werden. Ranken wachsen natürlich an Dschungelbäumen oder in Sümpfen.",
        "glasflasche": "Eine Glasflasche kann gecraftet werden, indem in einer Werkbank mit drei Glasblöcken ein V geformt wird.",
        "redstone-erz": "Redstone-Erz kann in den unteren sechzehn Schichten der Karte gefunden werden. Wenn es mit einer Eisenspitzhacke oder einer Spitzhacke aus hochwertigerem Material zerstört wird, droppt es eine gewisse Anzahl von Redstone. Um das Erz an und für sich zu erhalten, muss eine Spitzhacke mit der Verzauberung Behutsamkeit verwendet werden.",
        "smaragdblock": "Ein Smaragdblock kann gecraftet werden, indem neun Smaragde in einem 3x3-Raster in einer Werkbank platziert werden.",
        "granit": "Granit kann mit einer Spitzhacke abgebaut oder gecraftet werden, indem in der Werkbank Diorit und ein Netherquarz nebeneinander platziert werden.",
        "braune wolle": "Braune Wolle kann gecraftet werden, indem in einem Craftingfeld Brauner Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "goldener apfel": "Ein Goldener Apfel kann gecraftet werden, indem ein Apfel in das Feld ganz in der Mitte gelegt und dann von acht Goldbarren umgeben wird.",
        "birkenlaub": "Alles Laub kann erhalten werden, indem eine Schere mit dem gewünschten Laub benutzt wird.",
        "weiße wolle": "Weiße Wolle kann gecraftet werden, indem im Craftingfeld vier Fäden in einem 2x2-Raster platziert werden. Sie kann auch gecraftet werden, indem in einem Craftingfeld Knochenmehl neben Wolle einer beliebigen Farbe platziert wird.",
        "violetter teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.",
        "gebrannter ton": "Gebrannter Ton kann gecraftet werden, indem ein Tonblock in einem Ofen geschmolzen wird.",
        "zombieschädel": "Schädel erhält man, indem man mit einem geladenen Creeper die Kreatur explodieren lässt, deren Schädel man möchte.",
        "eisenfalltür": "Eine Eisenfalltür kann gecraftet werden, indem Eisenbarren in einem 2x2-Raster in einem Craftingfeld platziert werden.",
        "blumentopf": "Ein Blumentopf kann gecraftet werden, indem in einer Werkbank drei Ziegel in V-Form platziert werden.",
        "eisenerz": "Eisenerz kann erhalten werden, indem Eisenerzblöcke mit einer Spitzhacke aus Stein oder einem hochwertigerem Material abgebaut werden.",
        "tropenholzstufe": "Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.",
        "birkenholzstufe": "Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.",
        "tropenholztür": "Eine Tropenholztür kann gecraftet werden, indem sechs Tropenholzbretter in den ersten beiden Spalten senkrecht nach unten platziert werden.",
        "goldaxt": "Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "packeis": "Packeis kann in der seltenen Eiszapfentundra gefunden und nur mit einem Werkzeug mit der Verzauberung Behutsamkeit abgebaut werden.",
        "ziegel": "Ziegel können gecraftet werden, indem Ton in einem Ofen geschmolzen wird.",
        "hellblauer teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.",
        "toter busch": "Tote Büsche, auch nur Büsche genannt, werden mit einer Schere erhalten.",
        "spender": "Ein Spender kann gecraftet werden, indem Redstone im mittleren unteren Feld und Bruchstein in den übrigen Feldern außer im Feld ganz in der Mitte platziert werden.",
        "truhe": "Eine Truhe kann gecraftet werden, indem Holzbretter in alle Felder einer Werkbank mit Ausnahme des Feldes ganz in der Mitte platziert werden.",
        "rohes hühnchen": "Rohes Hühnchen wird beim Tod eines Huhns gedroppt.",
        "roher lachs": "Roher Lachs kann zufällig durch Angeln erhalten werden.",
        "haken": "Ein Haken kann gecraftet werden, indem in einer Werkbank ein Eisenbarren über einem Stock über einem Holzbrett platziert wird.",
        "eichenholztreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "befehlsblocklore": "Eine Befehlsblocklore kann nur durch Cheats erhalten werden.",
        "enderauge": "Ein Enderauge kann gecraftet werden, indem im Craftingfeld Lohenstaub neben einer Enderperle platziert wird.",
        "kohleblock": "Ein Kohleblock kann gecraftet werden, indem Kohle in einem 3x3-Raster in einem Craftingfeld platziert wird.",
        "netherstern": "Ein Netherstern kann erhalten werden, indem der Wither besiegt wird.",
        "kies": "Kies erhält man, indem Kiesblöcke zerkleinert werden.",
        "blaue wolle": "Blaue Wolle kann gecraftet werden, indem im Craftingfeld Blauer Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "netherquarz": "Netzerquarz kann erhalten werden, indem Netzquarzerz in einem Ofen geschmolzen wird.",
        "verrottetes fleisch": "Verrottetes Fleisch kann zufällig durch das Töten von Zombies erhalten werden.",
        "magenta teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.",
        "weiß gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "birkenholzzauntor": "Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "karotten": "Karotten können selten durch das Töten von Zombies erhalten werden, oder sie können zum Anpflanzen in Dörfern gefunden werden.",
        "violetter farbstoff": "Violetter Farbstoff kann gecraftet werden, indem im Craftingfeld Lapislazuli neben Rotem Farbstoff platziert wird.",
        "lapislazuliblock": "Ein Lapislazuliblock kann erhalten werden, indem eine Werkbank vollständig mit Lapislazuli ausgefüllt wird.",
        "obsidian": "Obsidian kann mit einer Diamantspitzhacke abgebaut oder hergestellt werden, indem Wasser über Lava platziert wird. ",
        "schallplatte mellohi": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "graue wolle": "Graue Wolle kann gecraftet werden, indem im Craftingfeld Grauer Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "redstonetruhe": "Eine Redstonetruhe kann gecraftet werden, indem in einem Craftingfeld ein Haken neben einer Truhe platziert wird.",
        "hellgrau gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "eisenspitzhacke": "Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert wird.",
        "roter pilz": "Rote Pilze können natürlich in schlecht beleuchteten Bereichen, Pilzbiomen oder im Nether gefunden werden.",
        "kugelfisch": "Ein Kugelfisch kann zufällig durch Angeln erhalten werden.",
        "smaragd": "Smaragde können durch den Abbau von Smaragderz gewonnen.",
        "holzschaufel": "Jede Art von Schaufel lässt sich craften, indem auf der Werkbank das gewünschte Material in das obere mittlere Feld gelegt wird und dann Stöcke in die beiden direkt darunter befindlichen Felder platziert werden.",
        "goldhelm": "Alle Helme werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des unteren mittleren Feldes und der obersten Reihe in einer Werkbank platziert wird.",
        "melone": "Eine Melone kommt natürlich in Dschungeln vor oder kann mithilfe aus in Güterloren in verlassenen Minen gefundenen Melonenkernen angebaut werden.",
        "tonblock": "Ton wird gewöhnlich auf dem Boden von Flüssen und Seen in flachen, runden Stellen gefunden. Tonblöcke können gewöhnlich auch in Sümpfen gefunden werden.",
        "amboss": "Ein Amboss kann gecraftet werden, indem in einer Werkbank drei Eisenblöcke in die oberste Reihe, ein Eisenbarren in das Feld ganz in der Mitte und dann drei Eisenbarren in der unteren Reihe platziert werden.",
        "tageslichtsensor": "Ein Tageslichtsensor kann gecraftet werden, indem in einer Werkbank drei Mal Glas in der oberen Reihe, drei Netherquarze in der mittleren Reihe und drei Holzstufen in der unteren Reihe platziert werden.",
        "leine": "Eine Leine kann gecraftet werden, indem ein Schleimball in einer Werkbank in das Feld ganz in der Mitte und dann Fäden in das obere linke, obere mittlere, mittlere linke und untere rechte Feld platziert werden.",
        "sandstein": "Sandstein kann in Wüsten gewonnen oder durch die Kombination von Sand in einem 2x2-Raster gecraftet werden.",
        "lederjacke": "Alle Brustrüstungen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des oberen mittleren Feldes in einer Werkbank platziert wird.",
        "schwarz gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "hellgrün gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "tnt-lore": "Eine TNT-Lore wird gecraftet, indem ein TNT in einer Werkbank über einer Lore platziert wird.",
        "uhr": "Eine Uhr wird hergestellt, indem ein Redstone in einer Werkbank im mittleren Feld platziert und von vier Goldbarren umgeben wird.",
        "schwarzer teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.",
        "kakao": "Kakao entsteht aus Kakaopflanzen, die im Dschungel natürlich vorkommen. Kakaobohnen werden in Minecraft als Brauner Farbstoff verwendet.",
        "goldbarren": "Goldbarren können erhalten werden, indem Golderz in einem Ofen geschmolzen wird.",
        "steinziegelstufe": "Eine Steinziegelstufe kann hergestellt werden, indem in einer Werkbank drei Steinziegel in einer Reihe platziert werden.",
        "clownfisch": "Ein Clownfisch kann zufällig durch Angeln erhalten werden.",
        "kürbiskerne": "Kürbiskerne können gecraftet werden, indem ein Kürbis in einem Craftingfeld platziert wird.",
        "bemooster steinziegel": "Ein bemooster Steinziegel kann gecraftet werden, indem Ranken in einer Werkbank im Feld neben Steinziegeln platziert werden. Ein bemooster Steinziegel kann auch natürlich in Festungen vorkommen.",
        "spinnennetz": "Spinnennetze erhält man durch die Verwendung einer Schere oder eines Schwerts, das mit Behutsamkeit verzaubert ist.",
        "milcheimer": "Ein Milcheimer kann durch einen Rechtsklick auf eine Kuh mit einem Eiseneimer erhalten werden.",
        "eisenhelm": "Alle Helme werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des unteren mittleren Feldes und der obersten Reihe in einer Werkbank platziert wird.",
        "gelb gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "hellgrau gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "diamant": "Diamanten erhält man, indem Diamanterz mit einer Spitzhacke aus Eisen oder einem hochwertigerem Material abgebaut wird.",
        "steinschwert": "Jede Art von Schwert lässt sich craften, indem auf einer Werkbank das gewünschte Material in das obere mittlere Feld sowie das Feld ganz in der Mitte platziert und dann ein Stock in das darunter befindliche Feld gelegt wird.",
        "bruchsteintreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "bett": "Ein Bett kann gecraftet werden, indem in einer Werkbank drei Mal Wolle in der oberen Reihe und drei Holzbretter in der mittleren Reihe platziert werden.",
        "birkenholz": "Alle Holzarten können erhalten werden, indem der entsprechende Baum zerstört wird.",
        "quarzstufe": "Eine Quarzstufe kann hergestellt werden, indem in einer Werkbank drei Quarzblöcke in einer Reihe platziert werden.",
        "schwamm": "Schwämme können durch Töten eines großen Wächters gewonnen oder zufällig in Ozeanmonumenten gefunden werden.",
        "skelettschädel": "Schädel erhält man, indem man mit einem geladenen Creeper die Kreatur explodieren lässt, deren Schädel man möchte.",
        "eimer": "Ein Eimer kann hergestellt werden, indem in einer Werkbank drei Eisenbarren V-förmig platziert werden.",
        "diamantschwert": "Jede Art von Schwert lässt sich craften, indem auf einer Werkbank das gewünschte Material in das obere mittlere Feld sowie das Feld ganz in der Mitte platziert und dann ein Stock in das darunter befindliche Feld gelegt wird.",
        "goldschaufel": "Jede Art von Schaufel lässt sich craften, indem auf der Werkbank das gewünschte Material in das obere mittlere Feld gelegt wird und dann Stöcke in die beiden direkt darunter befindlichen Felder platziert werden.",
        "fichtenholztreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "eisengitter": "Ein Eisengitter kann gecraftet werden, indem sechs Eisenbarren in die beiden unteren Reihen einer Werkbank platziert werden, Ein Eisengitter kann auch natürlich in Festungen vorkommen.",
        "rohes kaninchen": "Rohes Kaninchen kann zufällig durch das Töten eines Kaninchens erhalten werden.",
        "gelber teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld platziert wird.",
        "karottenrute": "Eine Karottenrute kann gecraftet werden, indem im Craftingfeld eine Angel im mittleren linken Feld und eine Karotte im unteren mittleren Feld platziert werden.",
        "rohes schweinefleisch": "Rohes Schweinefleisch kann durch das Töten eines Schweins erhalten werden.",
        "ofen": "Ein Ofen kann gecraftet werden, indem Bruchstein in alle Felder einer Werkbank mit Ausnahme des Feldes ganz in der Mitte platziert werden.",
        "netherziegelzaun": "Ein Netzziegelzaun kann gecraftet werden, indem sechs Netherziegel in die beiden unteren Reihen einer Werkbank platziert werden.",
        "zaun": "Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "diamantene pferderüstung": "Eine Pferderüstung kann zufällig in Verliesen, Netherfestungen, bei Schmieden, in Dschungeltempeln, Wüstentempeln und Truhen in Festungen gefunden werden.",
        "rote sandsteinstufe": "Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.",
        "birkenholzbrett": "Birkenholzbretter können erhalten werden, indem Birkenholz in einer Werkbank platziert wird.",
        "grundgestein": "Grundgestein kann in Minecraft nur durch Cheats gewonnen werden, Es ist der unterste Block des Spiels.",
        "sattel": "Sättel können nicht gecraftet werden, sondern nur in Truhen in Verliesen, verlassenen Minenschächten, Netherfestungen, Wüstentempeln oder Dschungeltempeln gefunden werden.",
        "hellgrauer farbstoff": "Hellgrauer Farbstoff kann gecraftet werden, indem im Craftingfeld zwei Mal Knochenmehl in einer senkrechten Reihe neben einem Tintenbeutel platziert wird.",
        "tropenbaumlaub": "Alles Laub kann erhalten werden, indem eine Schere mit dem gewünschten Laub benutzt wird.",
        "schallplatte blocks": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "kürbis": "Kürbisse sind in den meisten Biomen selten auf Grasblöcken zu finden.",
        "ofenkartoffel": "Eine Ofenkartoffel kann erhalten werden, indem eine Kartoffel in einem Ofen geschmolzen wird.",
        "leder": "Leder kann zufällig durch das Töten von Kühen oder Pferden erhalten werden.",
        "hellgrauer teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld gelegt wird.",
        "eisenstiefel": "Alle Stiefel lassen sich craften, indem das gewünschte Material im linken mittleren, linken unteren, rechten mittleren und rechten unteren Feld einer Werkbank platziert wird.",
        "endstein": "Endstein kann naturgemäß in der Ende-Dimension gefunden werden.",
        "kettenhose": "Eine Kettenrüstung kann durch den Handel mit einem Dorfbewohner oder einen seltenen Drop von einer Kreatur erhalten werden.",
        "hasenpfote": "Eine Hasenpfote kann in seltenen Fällen beim Töten eines Hasens erhalten werden.",
        "glas": "Glas wird erhalten, indem Sand in einem Ofen geschmolzen wird.",
        "stein": "Stein wird hergestellt, indem Bruchstein in einem Ofen geschmolzen wird.",
        "prismarin": "Prismarin kann gecraftet werden, indem Prismarinscherben in einem 2x2-Raster in einem Craftingfeld platziert werden.",
        "kompass": "Ein Kompass wird hergestellt, indem ein Redstone in einer Werkbank im mittleren Feld platziert und von vier Eisenbarren umgeben wird.",
        "grün gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "goldhose": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "befehlsblock": "Befehlsblöcke können in Minecraft nur durch Cheats erhalten werden.",
        "werfer": "Ein Werfer kann hergestellt werden, indem ein Bogen im mittleren Feld, Redstone direkt darunter und Bruchstein in allen anderen Feldern platziert werden.",
        "giftige kartoffel": "Eine Giftige Kartoffel droppt zufällig beim Ernten von Kartoffeln.",
        "apfel": "Äpfel droppen zufällig von Eichen und Schwarzeichenlaub. Sie können auch zufällig in Truhen in Festungen und Dörfern gefunden werden.",
        "rote blume": "Mohn kann naturgemäß auf Gras gefunden oder zufällig hergestellt werden, indem Knochenmehl auf Gras angewandt wird.",
        "magenta farbstoff": "Magenta Farbstoff kann gecraftet werden, indem in einem Craftingfeld Violetter Farbstoff neben Rosa Farbstoff platziert wird.",
        "brauner teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld gelegt wird.",
        "prismarinscherbe": "Prismarinscherben können durch das Besiegen von Wächtern und großen Wächtern erhalten werden.",
        "redstone-block": "Ein Redstone-Block kann gecraftet werden, indem neun Redstones in einem 3x3-Raster in einer Werkbank platziert werden.",
        "gelb gefärbte glasscheibe": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "löwenzahngelb": "Löwenzahngelb entspricht dem Gelben Farbstoff in Minecraft. Es kann gecraftet werden, indem ein Löwenzahn oder eine Sonnenblume in einem Craftingfeld platziert wird.",
        "akazienholztreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "sandsteinstufe": "Eine Sandsteinstufe kann hergestellt werden, indem in einer Werkbank drei Sandstein-Blöcke in einer Reihe platziert werden.",
        "grauer teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld gelegt wird.",
        "polierter granit": "Polierter Granit kann gecraftet werden, indem vier Mal Granit in einem 2x2-Raster in einer Werkbank platziert wird.",
        "lore": "Eine Lore kann gecraftet werden, indem fünf Eisenbarren U-förmig in einer Werkbank platziert werden.",
        "braun gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "türkis gefärbte glasscheibe": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "buch": "Ein Buch wird mithilfe eines 2x2-Rasters in einem Craftingfeld hergestellt, bei dem in das rechte untere Feld Leder und in allen anderen Feldern Papier platziert wird.",
        "güterlore": "Eine Güterlore wird gecraftet, indem eine Truhe in einem Craftingfeld über einer Lore platziert wird.",
        "akaziensetzling": "Akaziensetzlinge können zufällig erhalten werden, indem Akazienlaub zerstört wird.",
        "papier": "Brot kann gecraftet werden, indem in einer Werkbank drei Mal Zuckerrohr in einer Reihe platziert wird.",
        "goldharnisch": "Alle Brustrüstungen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des oberen mittleren Feldes in einer Werkbank platziert wird.",
        "türkis gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "pilzsuppe": "Die Pilzsuppe oder der Pilzeintopf wird gecraftet, indem in einer Werkbank ein Roter Pilz im mittleren linken Feld, ein Brauner Pilz im mittleren Feld und eine Schüssel im unteren mittleren Feld platziert werden.",
        "netherziegel": "Netherziegel kann mit einer Spitzhacke abgebaut oder gecraftet werden, indem in der Werkbank in einem 2x2-Raster vier Netherziegel platziert werden.",
        "magmacreme": "Magmacreme kann gecraftet werden, indem in einem Craftingfeld Lohenstaub neben einem Schleimball platziert wird.",
        "schnee": "Schnee kann gecraftet werden, indem Schneebälle in einem 2x2-Raster in einem Craftingfeld platziert werden.",
        "oranger farbstoff": "Oranger Farbstoff kann gecraftet werden, indem im Craftingfeld Roter Farbstoff neben einem Gelben Farbstoff platziert wird.",
        "trank": "Ein Trank wird mithilfe eines Braustands, eines Kessels und Wasserflaschen hergestellt.",
        "hellgrün gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "weiß gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "boot": "Ein Boot kann erhalten werden, indem fünf Holzbretter U-förmig platziert werden.",
        "dunkler prismarin": "Dunkle Prismarine können gecraftet werden, indem ein Tintenbeutel im mittleren Feld platziert und dann von acht Prismarinscherben umgeben wird.",
        "eichenholztür": "Eine Eichenholztür kann gecraftet werden, indem sechs Eichenbretter in den ersten beiden Spalten senkrecht nach unten platziert werden.",
        "kakao": "Kakao entsteht aus Kakaopflanzen, die im Dschungel natürlich vorkommen. Kakaobohnen werden in Minecraft als Brauner Farbstoff verwendet.",
        "eichenholz": "Alle Holzarten können erhalten werden, indem der entsprechende Baum zerstört wird.",
        "rote wolle": "Rote Wolle kann gecraftet werden, indem im Craftingfeld Roter Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "gebratenes hammelfleisch": "Gebratenes Hammelfleisch wird erhalten, indem Rohes Hammelfleisch in einem Ofen gebraten wird. Alternativ dazu droppen ein bis zwei Stücke Gebratenes Hammelfleisch, wenn ein brennendes Schaf stirbt.",
        "schwarzeichenholzzaun": "Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "eisentür": "Eine Eisentür kann gecraftet werden, indem sechs Eisenbarren in den ersten beiden Spalten senkrecht nach unten platziert werden.",
        "gemälde": "Ein Gemälde wird gecraftet, indem Wolle im mittleren Feld platziert und von acht Stöcken umgeben wird.",
        "fichtennadeln": "Alles Laub kann erhalten werden, indem eine Schere mit dem gewünschten Laub benutzt wird.",
        "rosa gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "akazienholzstufe": "Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.",
        "schwarzeichenholzstufe": "Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.",
        "gemeißelter sandstein": "Gemeißelter Sandstein kann hergestellt werden, indem im Craftingfeld eine Sandsteinstufe über einer anderen platziert wird.",
        "eichenholzbrett": "Eichenholzbretter können erhalten werden, indem Eichenholz in einer Werkbank platziert wird.",
        "gebratener lachs": "Gebratener Lachs wird erhalten, indem Lachs in einem Ofen gebraten wird.",
        "eisenschaufel": "Jede Art von Schaufel lässt sich craften, indem auf der Werkbank das gewünschte Material in das obere mittlere Feld gelegt wird und dann Stöcke in die beiden direkt darunter befindlichen Felder platziert werden.",
        "zaubertisch": "Ein Zaubertisch kann gecraftet werden, indem in der Werkbank ein Buch in das obere mittlere Feld, Diamanten in das mittlere linke und mittlere rechte Feld und Obsidian ganz in die Mitte und in alle Felder der untersten Reihe platziert werden.",
        "redstone-verstärker": "Ein Redstone-Verstärker kann gecraftet werden, indem glatter Stein in allen drei Feldern der untersten Reihe, Redstone ganz in der Mitte und Redstone-Fackeln links und rechts vom Redstone platziert werden.",
        "schallplatte far": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "grüner teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld gelegt wird.",
        "eisenbarren": "Eisenbarren können erhalten werden, indem Eisenerz in einem Ofen geschmolzen wird.",
        "orange wolle": "Orange Wolle kann gecraftet werden, indem im Craftingfeld Oranger Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "tropenbaumsetzling": "Tropenbaumsetzlinge können zufällig erhalten werden, indem Tropenbaumlaub zerstört wird.",
        "steinstufe": "Eine Steinstufe kann hergestellt werden, indem in einer Werkbank drei Stein-Blöcke in einer Reihe platziert werden.",
        "hellblau gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "türkiser farbstoff": "Türkiser Farbstoff kann gecraftet werden, indem im Craftingfeld Lapislazuli neben Kaktusgrün platziert wird.",
        "steak": "Rohes Rindfleisch kann zu Steak zubereitet werden, indem es in einem Ofen geschmolzen wird. Alternativ dazu besteht die Chance, dass Steak droppt, wenn eine brennende Kuh oder Moo stirbt.",
        "orange gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "blau gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "fichtenholzzaun": "Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "kohle": "Kohle erhält man, indem Steinkohleblöcke mit einer Spitzhacke aus Holz oder aus einem hochwertigerem Material abgebaut werden.",
        "kartoffeln": "Kartoffeln können selten durch das Töten von Zombies erhalten werden, oder sie können zum Anpflanzen in Dörfern gefunden werden.",
        "hellgrau gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "zauntor": "Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "ei": "Eier werden von Hühnern zufällig gelegt. Das Werfen eines Eis kann mitunter ein neues Küken spawnen.",
        "fichtenholzbrett": "Fichtenholzbretter können erhalten werden, indem Fichtenholz in einer Werkbank platziert wird.",
        "orange gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "akazienholz": "Alle Holzarten können erhalten werden, indem der entsprechende Baum zerstört wird.",
        "hellgraue wolle": "Hellgrau Wolle kann gecraftet werden, indem im Craftingfeld Hellgrauer Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "strohballen": "Ein Strohballen kann gecraftet werden, indem Weizen in einem 3x3-Raster in einer Werkbank platziert wird.",
        "ton": "Ton wird erhalten, indem man Tonblöcke mit einer nicht mit Behutsamkeit verzauberten Spitzhacke abbaut.",
        "schüssel": "Eine Schüssel kann hergestellt werden, indem in einer Werkbank drei Holzbretter V-förmig platziert werden.",
        "lederkappe": "Alle Helme werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des unteren mittleren Feldes und der obersten Reihe in einer Werkbank platziert wird.",
        "rosa gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "diamantbrustpanzer": "Alle Brustrüstungen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des oberen mittleren Feldes in einer Werkbank platziert wird.",
        "grau gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "gelb gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "schneemann": "Ein Schneegolem kann erschaffen werden, indem ein Kürbis auf zwei auf dem Boden stehende Schneeblöcke gesetzt wird.",
        "diamanterz": "Diamanterz kann in den unteren sechzehn Schichten der Karte gefunden werden. Diamanterz kann mit einer Spitzhacke aus Eisen oder hochwertigerem Material zerbrochen werden. Damit wird das Diamanterz zu einem Diamanten. Um das Erz zu erhalten, muss eine Spitzhacke mit der Verzauberung Behutsamkeit verwendet werden.",
        "banner": "Ein Banner kann gecraftet werden, indem sechs Mal Wolle in die beiden oberen Reihen und ein Stock im unteren mittleren Feld platziert werden. Das Banner nimmt die Farbe der ausgewählten Wolle an.",
        "steinaxt": "Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "feuerwerksstern": "Ein Feuerwerksstern kann gecraftet werden, indem in der Werkbank Schwarzpulver in das linke mittlere und Farbstoff einer beliebigen Farbe in das Feld ganz in der Mitte platziert werden. Außerdem kann ein Feuerwerksstern auch mit optionalen Materialien wie Diamanten, Glowstonestaub oder Federn gecraftet werden, die in der Werkbank direkt unterhalb des Farbstoffes platziert werden müssen.",
        "netherwarze": "Netherwarzen treten natürlich in Pflanzenform in Netherfestungen auf.",
        "rot gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "quarzblock": "Ein Quarzblock kann gecraftet werden, indem vier Mal Netherquarz in einem 2x2-Raster in einer Werkbank platziert wird.",
        "mohn": "Mohn kann naturgemäß auf Gras gefunden oder zufällig hergestellt werden, indem Knochenmehl auf Gras angewandt wird.",
        "akazienholzzaun": "Jede Art von Zaun kann gecraftet werden, indem ein Holzbrett, ein Stock und dann ein weiteres Holzbrett in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "kaktus": "Kaktus kann naturgemäß in der Wüsten-Biomen gefunden werden. ",
        "fichtenholztür": "Eine Fichtenholztür kann gecraftet werden, indem sechs Fichtenholzbretter in den ersten beiden Spalten senkrecht nach unten platziert werden.",
        "schallplatte cat": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "feuerzeug": "Ein Feuerzeug kann gecraftet werden, indem im Craftingfeld ein Eisenbarren links von einem Feuerstein platziert wird.",
        "goldbeinschutz": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "schleimball": "Schleimbälle droppen zufällig beim Töten von Schleimen.",
        "gebratenes schweinefleisch": "Gebratenes Schweinefleisch kann erhalten werden, indem Rohes Schweinefleisch in einem Ofen gebraten oder ein Schwein angezündet wird.",
        "polierter andesit": "Polierter Andesit kann gecraftet werden, indem vier Mal Andesit in einem 2x2-Raster in einer Werkbank platziert wird.",
        "prismarinziegel": "Prismarinziegel können gecraftet werden, indem Prismarinscherben in einem 3x3-Raster in einer Werkbank platziert werden.",
        "wither": "Ein Wither kann erschaffen werden, indem man drei Witherskelettschädel auf Seelensand gibt, der wiederum T-förmig auf dem Boden platziert wird.",
        "hellgrüner farbstoff": "Hellgrüner Farbstoff kann gecraftet werden, indem im Craftingfeld Kaktusgrün neben Knochenmehl platziert wird.",
        "blauer Teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld gelegt wird.",
        "tür": "Eine Tür kann gecraftet werden, indem sechs Bretter in den ersten beiden Spalten senkrecht nach unten platziert werden.",
        "stolperdraht": "Stolperdraht ist einfach eine Schnur neben einem Haken.",
        "zaubertisch": "Ein Zaubertisch kann gecraftet werden, indem in der Werkbank ein Buch in das obere mittlere Feld, Diamanten in das mittlere linke und mittlere rechte Feld und Obsidian ganz in die Mitte und in alle Felder der untersten Reihe platziert werden.",
        "türkiser teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld gelegt wird.",
        "polierter diorit": "Polierter Diorit kann gecraftet werden, indem vier Mal Diorit in einem 2x2-Raster in einer Werkbank platziert wird.",
        "goldstiefel": "Alle Stiefel lassen sich craften, indem das gewünschte Material im linken mittleren, linken unteren, rechten mittleren und rechten unteren Feld einer Werkbank platziert wird.",
        "eisenblock": "Ein Eisenblock kann gecraftet werden, indem Eisenbarren in einem 3x3-Raster in einer Werkbank platziert werden.",
        "akazienlaub": "Alles Laub kann erhalten werden, indem eine Schere mit dem gewünschten Laub benutzt wird.",
        "schwarzeichensetzling": "Schwarzeichensetzlinge können zufällig erhalten werden, indem Schwarzeichenlaub zerstört wird.",
        "diamantenhacke": "Alle Arten von Hacken können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke und obere mittlere Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "löwenzahn": "Löwenzahn wächst natürlich auf Gras oder kann zufällig hergestellt werden, indem Knochenmehl auf Gras verwendet wird.",
        "lapislazuli": "Kann erhalten werden, indem Lapislazulierz mit einer Spitzhacke aus Stein oder hochwertigerem Material abgebaut wird.",
        "zuckerrohr": "Zuckerrohr kann naturgemäß in der Nähe von Wasser gefunden werden.",
        "birkenholztür": "Eine Birkenholztür kann gecraftet werden, indem sechs Birkenholzbretter in den ersten beiden Spalten senkrecht nach unten platziert werden.",
        "kaktusgrün": "Kaktusgrün kann gecraftet werden, indem ein Kaktus in einem Ofen geschmolzen wird.",
        "goldblock": "Ein Goldblock kann gecraftet werden, indem Goldbarren in einem 3x3-Raster in einer Werkbank platziert werden.",
        "glatter sandstein": "Glatter Sandstein kann gecraftet werden, indem in einem Craftingfeld vier Mal Sandstein in einem 2x2-Raster platziert wird.",
        "magenta gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "notenblock": "Ein Notenblock wird gecraftet, indem ein Redstone in einer Werkbank im mittleren Feld platziert und von Holzbrettern umgeben wird.",
        "schnee-block": "Schnee kann gecraftet werden, indem Schneebälle in einem 2x2-Raster in einem Craftingfeld platziert werden.",
        "kreaturenschädel": "Schädel erhält man, indem man mit einem geladenen Creeper die Kreatur explodieren lässt, deren Schädel man möchte.",
        "diamantbeinschutz": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "roter sandstein": "Roter Sandstein kann gecraftet werden, indem vier Mal Roter Sand in einem 2x2-Craftingfeld platziert wird.",
        "orange gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "schleimblock": "Ein Schleimblock kann gecraftet werden, indem Schleimbälle in einem 3x3-Raster in einem Craftingfeld platziert werden.",
        "bücherregal": "Ein Bücherregal wird hergestellt, indem Bücher über die mittlere Reihe und Holzbretter in der oberen und unteren Reihe platziert werden.",
        "kuchen": "Kuchen kann gecraftet werden, indem in der Werkbank drei Eimer Milch in der obersten Reihe, Zucker im linken mittleren und im rechten mittleren Feld, ein Ei im Feld ganz in der Mitte und drei Mal Weizen in der untersten Reihe platziert werden.",
        "holzknopf": "Ein Holzknopf kann gecraftet werden, indem ein einziges Holzbrett in einem Craftingfeld platziert wird.",
        "gemeißelter quarzblock": "Ein Gemeißelter Quarzblock kann erhalten werden, indem in einer Werkbank eine Quarzstufe über einer anderen platziert wird.",
        "steinknopf": "Ein Steinknopf kann gecraftet werden, indem ein einziger glatter Stein in einem Craftingfeld platziert wird.",
        "glowstonestaub": "Glowstonestaub wird durch den Abbau von Glowstoneblöcken erhalten.",
        "hellgrün gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "bruchsteinmauer": "Eine Bruchsteinmauer wird gecraftet, indem sechs Bruchsteine in die beiden unteren Reihen einer Werkbank platziert werden.",
        "namensschild": "Namensschilder können nur auf drei Arten erhalten werden. Sie können in einer Truhe in einem Verlies gefunden werden. Beim Angeln können Namensschilder auch erhalten werden. Der Tausch gegen zwanzig bis zweiundzwanzig Smaragde bei einem Bibliothekar-Dorfbewohner stellt die letzte Möglichkeit für den Erwerb eines Namensschildes dar.",
        "schwarzpulver": "Schwarzpulver kann zufällig durch das Töten von Creepern erhalten werden.",
        "lohenstaub": "Lohenstaub kann erhalten werden, indem eine Lohenrute in einer Werkbank platziert wird.",
        "braustand": "Ein Braustand kann gecraftet werden, indem eine Lohenrute ganz in die Mitte und drei Bruchsteine in der untersten Reihe der Werkbank platziert werden.",
        "fackel": "Ein Fackel kann gecraftet werden, indem ein Stück Kohle über einem Stock platziert wird.",
        "gelbe wolle": "Gelbe Wolle kann gecraftet werden, indem im Craftingfeld Gelber Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "melone": "Eine Melone kommt natürlich in Dschungeln vor oder kann mit Melonenkernen angebaut werden, die in Güterloren in verlassenen Minen gefunden wurden.",
        "schallplatte wait": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "glitzernde melone": "Eine Glitzernde Melone kann hergestellt werden, indem eine Melone in einer Werkbank im mittleren Feld platziert und von acht Goldklumpen umgeben wird.",
        "netherrack": "Netherrack oder Netherstein kann gewöhnlich in der gesamten Nether-Dimension gefunden werden.",
        "lederjacke": "Alle Brustrüstungen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des oberen mittleren Feldes in einer Werkbank platziert wird.",
        "holzstufe": "Eine Holzstufe kann hergestellt werden, indem in einer Werkbank drei Holzbretter in einer Reihe platziert werden.",
        "netherziegeltreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "eis": "Eis kommt natürlicherweise in Schnee-Biomen vor. Wenn es zerbrochen oder neben einer Hitzequelle platziert wird, schmilzt es zu Wasser. Um einen Eisblock zu erhalten, muss er mit einer Spitzhacke mit der Verzauberung Behutsamkeit abgebaut werden.",
        "großer farn": "Großer Farn kommt natürlicherweise in Dschungel-, Taiga- und Riesentaiga-Biomen vor.",
        "netherziegelstufe": "Eine Netherziegelstufe kann hergestellt werden, indem in einer Werkbank drei Netherziegel in einer Reihe platziert werden.",
        "fichtenholzstufe": "Alle Arten von Stufen können gecraftet werden, indem eine Reihe der Werkbank mit dem gewünschten Material gefüllt wird.",
        "eisenhacke": "Alle Arten von Hacken können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke und obere mittlere Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "farn": "Farn kommt natürlicherweise in Dschungel-, Taiga- und Riesentaiga-Biomen vor.",
        "seelaterne": "Eine Seelaterne kann gecraftet werden, indem Prismarinscherben in die vier Ecken einer Werkbank platziert und in die anderen Felder Prismarinkristalle gegeben werden.",
        "keks": "Ein Keks kann gecraftet werden, indem in der Werkbank in einer Reihe Weizen links und rechts von Kakaobohnen platziert wird.",
        "melonenkerne": "Melonenkerne können gecraftet werden, indem eine Melonenscheibe in einem Craftingfeld platziert wird.",
        "goldklumpen": "Goldklumpen können gecraftet werden, indem ein einziger Goldbarren in einem Craftingfeld platziert wird. Außerdem können sie zufällig durch das Töten eines Zombie-Pigmen erhalten werden.",
        "redstone-erz": "Redstone-Erz kann in den unteren sechzehn Schichten der Karte gefunden werden. Wenn es mit einer Eisenspitzhacke oder einer Spitzhacke aus hochwertigerem Material zerstört wird, droppt es eine gewisse Anzahl von Redstone. Um das Erz an und für sich zu erhalten, muss eine Spitzhacke mit der Verzauberung Behutsamkeit verwendet werden.",
        "diamanthelm": "Alle Helme werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des unteren mittleren Feldes und der obersten Reihe in einer Werkbank platziert wird.",
        "fichtenholzzauntor": "Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "goldhacke": "Alle Arten von Hacken können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke und obere mittlere Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "akazienholzbrett": "Akazienholzbretter können erhalten werden, indem Akazienholz in einer Werkbank platziert wird.",
        "diamantspitzhacke": "Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert wird.",
        "lapislazulierz": "Lapislazulierz kann nur erhalten werden, indem eine Spitzhacke mit der Verzauberung Behutsamkeit verwendet wird.",
        "rohes hammelfleisch": "Rohes Hammelfleisch kann durch das Töten eines Schafs erhalten werden.",
        "quarztreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "ziegelstein-block": "Ein Ziegelstein-Block kann gecraftet werden, indem Tonziegel in einem 2x2-Raster in einem Craftingfeld platziert werden.",
        "bruchsteinstufe": "Eine Bruchsteinstufe kann hergestellt werden, indem in einer Werkbank drei Bruchstein-Blöcke in einer Reihe platziert werden.",
        "smaragderz": "Smaragderz kann nur im Untergrund von Extremen Bergen zwischen den Schichten vier und zweiunddreißig gefunden werden. Es kann mit einer Eisenspitzhacke oder besser abgebaut werden, um Smaragde zu erhalten. Um das Erz selbst zu erhalten, wird eine Spitzhacke mit der Verzauberung Behutsamkeit benötigt.",
        "gelbe blume": "Löwenzahn wächst natürlich auf Gras oder kann zufällig hergestellt werden, indem Knochenmehl auf Gras verwendet wird.",
        "kürbislaternen": "Eine Kürbislaterne wird gecraftet, indem ein Kürbis in einer Werkbank über einer Fackel platziert wird.",
        "rot gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "eisenbeinschutz": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "rosa gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "schwarzer farbstoff": "Ein Tintelbeutel wird in Minecraft als Schwarzer Farbstoff verwendet.",
        "holzhacke": "Alle Arten von Hacken können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke und obere mittlere Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "violett gefärbtes glas": "Alle Arten von gefärbtem Glas lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Glas umgeben wird.",
        "güterlore": "Eine Güterlore wird gecraftet, indem eine Truhe in einem Craftingfeld über einer Lore platziert wird.",
        "sensorschiene": "Eine Sensorschiene kann gecraftet werden, indem eine Steindruckplatte im Feld ganz in der Mitte, Redstone im unteren mittleren Feld und Eisenbarren in den Feldern der rechten und linken Spalte platziert werden.",
        "türkise wolle": "Türkise Wolle kann gecraftet werden, indem im Craftingfeld Türkiser Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "eisenbrustpanzer": "Alle Brustrüstungen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des oberen mittleren Feldes in einer Werkbank platziert wird.",
        "bruchstein": "Bruchstein kann erhalten werden, indem Stein mit einer Spitzhacke abgebaut wird.",
        "schwarzeichenholztreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "creeperkopf": "Schädel erhält man, indem man mit einem geladenen Creeper die Kreatur explodieren lässt, deren Schädel man möchte.",
        "karotte": "Karotten können selten durch das Töten von Zombies erhalten werden, oder sie können zum Anpflanzen in Dörfern gefunden werden.",
        "kaninchenfell": "Kaninchenfell kann zufällig durch das Töten eines Kaninchens erhalten werden.",
        "gras": "Wenn Gras mit einer gewöhnlichen Schaufel geerntet wird, verwandelt es sich in Erde. Um einen Grasblock zu erhalten, muss eine Schaufel mit der Verzauberung Behutsamkeit verwendet werden.",
        "schallplatte strad": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "birkensetzlinge": "Birkensetzlinge können zufällig erhalten werden, indem Birkenlaub zerstört wird.",
        "moosstein": "Bemooster Bruchstein oder früher Moosstein kann gecraftet werden, indem Ranken in einer Werkbank im Feld neben einem Bruchstein platziert werden. Er kann auch natürlicherweise in verschiedenen Verliesen gefunden werden.",
        "rosa farbstoff": "Rosa Farbstoff kann gecraftet werden, indem im Craftingfeld Knochenmehl neben Rotem Farbstoff platziert wird.",
        "redstone-fackel": "Eine Redstone-Fackel wird gecraftet, indem ein Redstone in einem Craftingfeld über einer Fackel platziert wird.",
        "grün gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "hohes gras": "Hohes Gras, welches im Inventar Gras genannt wird, wächst auf Grasblöcken in bestimmten Biomen. Knochenmehl kann auf einem Grasblock verwendet werden, um Hohes Gras oder gelegentlich Blumen wachsen zu lassen.",
        "schwarze wolle": "Schwarze Wolle kann gecraftet werden, indem im Craftingfeld ein Tintenbeutel neben Wolle einer beliebigen Farbe platziert wird.",
        "weizen": "Weizen kann natürlicherweise in Dörfern gefunden oder aus Samen angebaut werden, die durch das Zerstören von Hohem Gras erhalten werden.",
        "enderperle": "Enderperlen können zufällig durch das Töten von Endermen erhalten werden.",
        "moosstein": "Bemooster Bruchstein oder früher Moosstein kann gecraftet werden, indem Ranken in einer Werkbank im Feld neben einem Bruchstein platziert werden. Er kann auch natürlicherweise in verschiedenen Verliesen gefunden werden.",
        "angel": "Eine Angel wird gecraftet, indem in einem Craftingfeld drei Stöcke in einer diagonalen Linie und dann zwei Mal Faden unter dem oberen rechten Stöck platziert werden.",
        "knochenmehl": "Knochenmehl kann gecraftet werden, indem ein Knochen in einem Craftingfeld platziert wird.",
        "quarz": "Netzerquarz kann erhalten werden, indem Netzquarzerz in einem Ofen geschmolzen wird.",
        "schwarzeichenholzbrett": "Schwarzeichenholzbretter können erhalten werden, indem Schwarzeichenholz in einer Werkbank platziert wird.",
        "antriebsschiene": "Eine Antriebsschiene kann gecraftet werden, indem ein Stock im Feld ganz in der Mitte, Redstone im unteren mittleren Feld und Goldbarren in den Feldern der rechten und linken Spalte platziert werden.",
        "leuchtfeuer": "Ein Leuchtfeuer kann gecraftet werden, indem in einer Werkbank ein Netherstern ganz in der Mitte, drei Obsidiane in den Feldern der untersten Reihe und fünf Mal Glas in den verbleibenden Feldern platziert werden.",
        "blau gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "schwarzeichenholztür": "Eine Schwarzeichenholztür kann gecraftet werden, indem sechs Schwarzeichenholzbretter in den ersten beiden Spalten senkrecht nach unten platziert werden.",
        "eisengolem": "Ein Eisengolem kann ähnlich wie ein Schneegolem erschaffen werden, indem ein Kürbiskopf auf zwei Eisenblöcken platziert wird. Danach muss links und rechts des Eisenblocks ganz in der Mitte jeweils ein Eisenblock platziert werden.",
        "fichtenholz": "Alle Holzarten können erhalten werden, indem der entsprechende Baum zerstört wird.",
        "rosa wolle": "Rosa Wolle kann gecraftet werden, indem im Craftingfeld Rosa Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "feuerkugel": "Eine Feuerkugel kann gecraftet werden, indem in der Werkbank Lohenstaub im mittleren linken Feld, Kohle im Feld ganz in der Mitte und Schwarzpulver im unteren mittleren Feld platziert wird.",
        "akazienholztür": "Eine Akazienholztür kann gecraftet werden, indem sechs Akazienholzbretter in den ersten beiden Spalten senkrecht nach unten platziert werden.",
        "eisenbeinschutz": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "schallplatte chirp": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "eichenlaub": "Alles Laub kann erhalten werden, indem eine Schere mit dem gewünschten Laub benutzt wird.",
        "pfeil": "Ein Pfeil kann gecraftet werden, indem in der Werkbank ein Feuerstein in das obere mittlere Feld, ein Stock in das Feld ganz in der Mitte und eine Feder in das untere mittlere Feld gelegt werden.",
        "holzaxt": "Alle Arten von Äxten können gecraftet werden, indem das gewünschte Material in der Werkbank in das obere linke, obere mittlere und mittlere linke Feld und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert werden.",
        "glasscheibe": "Eine Glasscheibe kann gecraftet werden, indem sechs Glasblöcke in die beiden unteren Reihen einer Werkbank platziert werden.",
        "goldhelm": "Alle Helme werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des unteren mittleren Feldes und der obersten Reihe in einer Werkbank platziert wird.",
        "endertruhe": "Eine Endertruhe kann gecraftet werden, indem in einer Werkbank ein Enderauge im Feld ganz in der Mitte platziert und von acht Obsidian-Blöcken umgeben wird.",
        "hellblaue wolle": "Hellblaue Wolle kann gecraftet werden, indem in einem Craftingfeld Hellblauer Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "faden": "Faden kann zufällig durch das Töten von Spinnen oder das Zerstören von Spinnennetzen erhalten werden.",
        "rote sandsteintreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "violette wolle": "Violette Wolle kann gecraftet werden, indem im Craftingfeld Violetter Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "türkis gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird.",
        "schwarz gefärbter ton": "Alle Arten gefärbten Tons lassen sich craften, indem der gewünschte Farbstoff im mittleren Feld platziert und von Gebranntem Ton umgeben wird.",
        "verzaubertes buch": "Verzauberte Bücher können in den Truhen der Verliese, Festungen, Wüsten- und Dschungeltempel und Minen gefunden werden.",
        "knopf": "Ein Knopf kann gecraftet werden, indem ein einziger glatter Stein oder ein einziges Holzbrett in einem Craftingfeld platziert wird.",
        "hellgrüne wolle": "Hellgrüne Wolle kann gecraftet werden, indem im Craftingfeld Hellgrüner Farbstoff neben Wolle einer beliebigen Farbe platziert wird.",
        "grobe erde": "Grobe Erde kann erhalten werden, indem Erde aus Riesentaiga-, Tafelberg- oder Savanne-Biomen zerbrochen wird.",
        "ghastträne": "Ghasttränen können selten durch das Töten von Ghasts erhalten werden.",
        "antriebslore": "Eine Antriebslore wird gecraftet, indem ein Ofen in einem Craftingfeld über einer Lore platziert wird.",
        "weizen": "Weizen kann natürlicherweise in Dörfern gefunden oder aus Samen angebaut werden, die durch das Zerstören von Hohem Gras erhalten werden.",
        "seelensand": "Seelensand kann gewöhnlich in der gesamten Nether-Dimension gefunden werden.",
        "brauner pilz": "Braune Pilze können natürlich in schlecht beleuchteten Bereichen, Pilzbiomen oder im Nether gefunden werden.",
        "kettenhaube": "Eine Kettenrüstung kann durch den Handel mit einem Dorfbewohner oder einen seltenen Drop von einer Kreatur erhalten werden.",
        "beschriebenes buch": "Ein Beschriebenes Buch entsteht, wenn ein Buch und Feder signiert wird.",
        "fichtensetzling": "Fichtensetzlinge können zufällig erhalten werden, indem Fichtennadeln zerstört werden.",
        "eichensetzling": "Eichensetzlinge können zufällig erhalten werden, indem Eichenlaub zerstört wird.",
        "nachtlichtsensor": "Durch einen Rechtsklick auf einen Tageslichtsensor kann dieser in einen Nachtlichtsensor umgewandelt werden.",
        "sandsteintreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "redstone-lampe": "Eine Redstone-Lampe wird hergestellt, indem ein Glowstone in einer Werkbank im mittleren Feld platziert und von vier Redstones umgeben wird.",
        "werkbank": "Eine Werkbank kann gecraftet werden, indem Holzbretter in einem 2x2-Raster in einem Craftingfeld platziert werden.",
        "glowstone": "Glowstone kann auf den Decken in der Nether-Dimension gefunden werden.",
        "holzdruckplatte": "Eine Holzdruckplatte lässt sich craften, indem zwei Holzbretter horizontal nebeneinander in das Craftingfeld gelegt werden.",
        "holzkohle": "Holzkohle wird erhalten, indem Holzblöcke in einem Ofen geschmolzen werden.",
        "kettenstiefel": "Eine Kettenrüstung kann durch den Handel mit einem Dorfbewohner oder einen seltenen Drop von einer Kreatur erhalten werden.",
        "leiter": "Eine Leiter kann gecraftet werden, indem Stöcke in alle Felder einer Werkbank mit Ausnahme des Feldes ganz in der Mitte und des unteren mittleren Feldes platziert werden.",
        "bemooster bruchstein": "Bemooster Bruchstein oder früher Moosstein kann gecraftet werden, indem Ranken in einer Werkbank im Feld neben einem Bruchstein platziert werden. Er kann auch natürlicherweise in verschiedenen Verliesen gefunden werden.",
        "goldspitzhacke": "Alle Arten von Spitzhacken können gecraftet werden, indem das gewünschte Material drei Mal in der oberen Reihe der Werkbank und dann jeweils ein Stock in das Feld ganz in der Mitte und das in der Mitte der unteren Reihe platziert wird.",
        "weizenkörner": "Weizenkörner können zufällig beim Zerstören von Hohem Gras gefunden werden.",
        "akazienholzzauntor": "Jede Art von Zauntor kann gecraftet werden, indem ein Stock, ein Holzbrett und dann ein weiterer Stock in einer Werkbank in den beiden unteren Reihen platziert werden.",
        "birkenholztreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "schallplatte ward": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "schallplatte": "Eine zufällige Schallplatte kann droppen, wenn ein Creeper vom Pfeil eines Skeletts getötet wird. Alternativ dazu können Musikschallplatten auch in acht Prozent der Truhen in Verliesen gefunden werden.",
        "verzauberter goldener apfel": "Ein verzauberter Goldener Apfel kann gecraftet werden, indem ein Apfel in das Feld ganz in der Mitte gelegt und dann von acht Goldblöcken umgeben wird.",
        "weißer teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld gelegt wird.",
        "eisenschwert": "Jede Art von Schwert lässt sich craften, indem auf einer Werkbank das gewünschte Material in das obere mittlere Feld sowie das Feld ganz in der Mitte platziert und dann ein Stock in das darunter befindliche Feld gelegt wird.",
        "diamantbeinschutz": "Alle Hosen werden gecraftet, indem das gewünschte Material in allen Feldern mit Ausnahme des mittleren und des unteren mittleren Feldes in einer Werkbank platziert werden.",
        "gemeißelter roter sandstein": "Gemeißelter roter Sandstein kann gecraftet werden, indem im Craftingfeld eine rote Sandsteinstufe über einer anderen roten Sandsteinstufe platziert wird.",
        "steinziegeltreppe": "Jede Art von Treppe kann gecraftet werden, indem das gewünschte Material in allen Feldern der Werkbank mit Ausnahme des oberen mittleren, oberen rechten und mittleren rechten Feldes platziert wird.",
        "sruckplatte": "Eine Druckplatte lässt sich craften, indem entweder zwei glatte Steine oder zwei Holzbretter horizontal nebeneinander in das Craftingfeld gelegt werden.",
        "tropenholzbrett": "Tropenholzbretter können erhalten werden, indem Tropenholz in einer Werkbank platziert wird.",
        "grüne wolle": "Grüne Wolle kann gecraftet werden, indem im Craftingfeld Kaktusgrün neben Wolle einer beliebigen Farbe platziert wird.",
        "zuckerrohr": "Zuckerrohr kommt naturgemäß in der Nähe von Wasser vor.",
        "bogen": "Ein Bogen kann gecraftet werden, indem in einer Werkbank drei Mal Faden in den Feldern der rechten Spalte und dann drei Stöcke in Form eines Kleinerzeichens neben den Fäden platziert werden.",
        "hellgrüner teppich": "Jede Art von Teppich lässt sich craften, indem zwei Mal Wolle der gleichen Farbe nebeneinander in das Craftingfeld gelegt wird.",
        "feuerstein": "Flint droppt zufällig beim Zerbrechen von Kies.",
        "schwarz gefärbte glasscheibe": "Alle verschiedenen gefärbten Glasscheiben lassen sich craften, indem Glas gleicher Farbe in den unteren beiden Reihen horizontal platziert wird."
    }
};
